version: '3.8'

services:
  backend:
    image: backend-dev
    container_name: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
    ports:
      - "3000:3000"
    networks:
      - shared-network
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://awais:Awais12345@postgres-dev:5432/devdb?sslmode=disable
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
      - CHOKIDAR_USEPOLLING=true
      - DEBUG=express:*
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres-dev:
        condition: service_healthy
      redis-dev:
        condition: service_healthy

  frontend:
    image: frontend-dev
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - VITE_API_URL=http://localhost:3000
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - VITE_DEBUG=true
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - shared-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  postgres-dev:
    container_name: postgres-dev
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U awais -d devdb"]
      interval: 5s
      timeout: 5s
      retries: 20
    environment:
      POSTGRES_USER: awais
      POSTGRES_PASSWORD: Awais12345
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    networks:
      - shared-network
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis-dev:
    image: redis/redis-stack:latest
    container_name: redis-dev
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - shared-network
    volumes:
      - redis_dev_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  shared-network:
    driver: bridge