version: '3.8'


services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.prod
        
        ports:
            -   "80:80"

    backend:
        init: true
        stop_grace_period: 10s
        
        build:
            context: ./backend
            dockerfile: Dockerfile.prod

        environment:
            -   NODE_ENV=production
            -   DATABASE_URL=postgres://awais:Awais12345@postgres-prod:5432/proddb

        depends_on:
            postgres-prod:
                condition:  service_healthy
            
            redis-prod:
                condition:  service_started

    postgres-prod:
        image: postgres:15
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U awais -d proddb"]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            -   POSTGRES_USER=awais
            -   POSTGRES_PASSWORD=Awais12345
            -   POSTGRES_DB=proddb
        volumes:
            -   postgres_prod_data:/var/lib/postgresql/data

    redis-prod:
        image: redis:7
        volumes:
            -   redis_prod_data:/data

volumes:
    postgres_prod_data:
    redis_prod_data: