FROM node:18-alpine AS builder
WORKDIR /app

COPY . .
RUN npm ci && npm run build


FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/prisma ./prisma

RUN npx prisma generate

CMD [ "node", "dist/index.js" ]