FROM node:18-alpine

# Install essential dependencies
RUN apk add --no-cache openssl python3 make g++ postgresql-client

WORKDIR /app

# Copy dependency files first
COPY package*.json ./
COPY prisma/schema.prisma ./prisma/

# Install dependencies
RUN npm install && npx prisma generate

# Copy source code
COPY . .

# Wait for Postgres + run migrations + start server
CMD ["sh", "-c", "until PGPASSWORD=Awais12345 pg_isready -h postgres-dev -p 5432 -U awais -d devdb; do sleep 2; echo 'Waiting for Postgres...'; done && npx prisma migrate deploy && npm run dev"]